name: party_bomb
description: Word party game

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+9

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  audioplayers: ^3.0.1
  shared_preferences: ^2.0.15
  animated_splash_screen: ^1.3.0
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.1.7
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  simple_shadow: ^0.3.0
  google_mobile_ads: ^2.3.0
  wakelock: ^0.6.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  universal_io: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/explosion-6801.mp3
    - assets/sounds/wall-clock-ticks-quartz-clock-25480.mp3
    - assets/images/flag-pl_android.png
    - assets/images/gb_android.png
    - assets/images/flag-ge_android.png
    - assets/images/flag-se_android.png

